"""empty message

Revision ID: b52c2ed70369
Revises: 1716e79c3a7c
Create Date: 2022-08-18 19:14:26.705312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b52c2ed70369'
down_revision = '1716e79c3a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
